"""initial schema: all tables

Revision ID: 67e09ba4b9d6
Revises: 
Create Date: 2026-06-24 16:36:46.032544
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e09ba4b9d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_audit_logs'))
    )
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_admin_id'), ['admin_id'], unique=False)

    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('body_key_or_text', sa.Text(), nullable=False),
    sa.Column('segment', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('draft', 'queued', 'sending', 'sent', 'failed', 'cancelled', name='broadcast_status_enum', native_enum=False, length=16), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcasts'))
    )
    with op.batch_alter_table('broadcasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broadcasts_admin_id'), ['admin_id'], unique=False)

    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title_key', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.Enum('affiliate_link', 'paid_access', name='offer_kind_enum', native_enum=False, length=24), server_default='affiliate_link', nullable=False),
    sa.Column('base_url', sa.String(length=1024), nullable=False),
    sa.Column('requires_payment', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('price_amount', sa.Integer(), nullable=True),
    sa.Column('price_currency', sa.String(length=16), nullable=True),
    sa.Column('delivery_type', sa.Enum('external_link', 'access_link', 'file_ref', 'access_code', 'text', name='delivery_type_enum', native_enum=False, length=32), server_default='external_link', nullable=False),
    sa.Column('delivery_payload', sa.Text(), nullable=True),
    sa.Column('jurisdiction_allowlist', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers')),
    sa.UniqueConstraint('code', name=op.f('uq_offers_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('lang', sa.Enum('en', 'ru', name='lang_enum', native_enum=False, length=8), server_default='en', nullable=False),
    sa.Column('status', sa.Enum('active', 'blocked', 'flagged', name='user_status_enum', native_enum=False, length=16), server_default='active', nullable=False),
    sa.Column('age_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jurisdiction_code', sa.String(length=16), nullable=True),
    sa.Column('jurisdiction_attested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marketing_opt_in', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('id', name='uq_users_telegram_id')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_event_id', sa.String(length=128), nullable=True),
    sa.Column('dedupe_hash', sa.String(length=128), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('received', 'processed', 'failed', name='webhook_status_enum', native_enum=False, length=16), server_default='received', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events')),
    sa.UniqueConstraint('dedupe_hash', name=op.f('uq_webhook_events_dedupe_hash')),
    sa.UniqueConstraint('external_event_id', name=op.f('uq_webhook_events_external_event_id'))
    )
    op.create_table('broadcast_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broadcast_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'failed', 'skipped_optout', name='recipient_status_enum', native_enum=False, length=24), server_default='queued', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], name=op.f('fk_broadcast_recipients_broadcast_id_broadcasts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_broadcast_recipients_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcast_recipients'))
    )
    with op.batch_alter_table('broadcast_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broadcast_recipients_broadcast_id'), ['broadcast_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_broadcast_recipients_user_id'), ['user_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('xrocket', 'manual', name='payment_provider_enum', native_enum=False, length=16), nullable=False),
    sa.Column('provider_invoice_id', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('created', 'pending', 'paid', 'expired', 'failed', 'refunded', name='payment_status_enum', native_enum=False, length=16), server_default='created', nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_payments_offer_id_offers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_payments_idempotency_key')),
    sa.UniqueConstraint('provider_invoice_id', name=op.f('uq_payments_provider_invoice_id'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_referrals_offer_id_offers')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_referrals_owner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referrals')),
    sa.UniqueConstraint('code', name=op.f('uq_referrals_code'))
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referrals_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('support_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('lang', sa.Enum('en', 'ru', name='lang_enum_support', native_enum=False, length=8), server_default='en', nullable=False),
    sa.Column('state', sa.Enum('open', 'answered', 'escalated', 'closed', name='support_state_enum', native_enum=False, length=16), server_default='open', nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('last_message', sa.Text(), nullable=True),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_support_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_requests'))
    )
    with op.batch_alter_table('support_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_requests_user_id'), ['user_id'], unique=False)

    op.create_table('clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.Enum('telegram', 'landing', 'external', name='click_source_enum', native_enum=False, length=16), server_default='telegram', nullable=False),
    sa.Column('ip_hash', sa.String(length=128), nullable=True),
    sa.Column('ua_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_clicks_offer_id_offers')),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], name=op.f('fk_clicks_referral_id_referrals')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_clicks_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clicks'))
    )
    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clicks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clicks_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clicks_referral_id'), ['referral_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clicks_user_id'), ['user_id'], unique=False)

    op.create_table('conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('click_id', sa.Integer(), nullable=True),
    sa.Column('referral_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('partner_conversion_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='conversion_status_enum', native_enum=False, length=16), server_default='pending', nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('source', sa.Enum('postback', 'callback', 'manual', name='conversion_source_enum', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['click_id'], ['clicks.id'], name=op.f('fk_conversions_click_id_clicks')),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_conversions_offer_id_offers')),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], name=op.f('fk_conversions_referral_id_referrals')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversions')),
    sa.UniqueConstraint('partner_conversion_id', name=op.f('uq_conversions_partner_conversion_id'))
    )
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversions_click_id'), ['click_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversions_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversions_referral_id'), ['referral_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversions_user_id'), ['user_id'], unique=False)

    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('conversion_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('delivery_type', sa.Enum('external_link', 'access_link', 'file_ref', 'access_code', 'text', name='delivery_type_enum_offer', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='delivery_status_enum', native_enum=False, length=16), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversion_id'], ['conversions.id'], name=op.f('fk_deliveries_conversion_id_conversions')),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_deliveries_offer_id_offers')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_deliveries_payment_id_payments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_deliveries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_deliveries_dedupe_key'))
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_conversion_id'), ['conversion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_user_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_payment_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_offer_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_conversion_id'))

    op.drop_table('deliveries')
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversions_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversions_referral_id'))
        batch_op.drop_index(batch_op.f('ix_conversions_offer_id'))
        batch_op.drop_index(batch_op.f('ix_conversions_click_id'))

    op.drop_table('conversions')
    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clicks_user_id'))
        batch_op.drop_index(batch_op.f('ix_clicks_referral_id'))
        batch_op.drop_index(batch_op.f('ix_clicks_offer_id'))
        batch_op.drop_index(batch_op.f('ix_clicks_created_at'))

    op.drop_table('clicks')
    with op.batch_alter_table('support_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_requests_user_id'))

    op.drop_table('support_requests')
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_offer_id'))

    op.drop_table('referrals')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_offer_id'))

    op.drop_table('payments')
    with op.batch_alter_table('broadcast_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broadcast_recipients_user_id'))
        batch_op.drop_index(batch_op.f('ix_broadcast_recipients_broadcast_id'))

    op.drop_table('broadcast_recipients')
    op.drop_table('webhook_events')
    op.drop_table('users')
    op.drop_table('offers')
    with op.batch_alter_table('broadcasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broadcasts_admin_id'))

    op.drop_table('broadcasts')
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_admin_id'))

    op.drop_table('admin_audit_logs')
    # ### end Alembic commands ###
